name = "MyProject"
uuid = "a9f7c895-4dd4-40e1-9647-891da5b9f757"
authors = ["Daisuke1988 <daisuke.nakamura.kuhachi.felix@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Expectations = "2fe49d83-0758-5602-8f54-1f90ad0d522b"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
